---
kind: "pipeline"
type: "docker"
name: "deployment"

steps:
        - name: "Install the dependencies"
          image: "registry.kalehmann.de/testing/wetterobservatoriumweb:latest"
          commands:
                  - "composer install --no-dev --classmap-authoritative"
        - name: "Deploy the website"
          image: "registry.kalehmann.de/testing/wetterobservatoriumweb:latest"
          commands:
                  - 'echo "$${ENV_FILE}" | tr " " "\n" > .env'
                  - 'lftp -e "
                      set ftp:ssl-force true;
                      set ssl:verify-certificate yes;
                      open -u $${USER},$${PASSWORD} $${SERVER};
                      mirror
                        --delete
                        --exclude=^.dockerignore
                        --exclude=^.drone.yaml
                        --exclude=^.git
                        --exclude=^doc
                        --exclude=^docker
                        --exclude=^Dockerfile
                        --exclude=^scripts
                        --exclude=^tests
                        --parallel=20
                        --reverse
                        $(pwd)
                        public_html/blumenwetter-kalehmann-de;
                      exit;"'
          depends_on:
                  - "Install the dependencies"
          environment:
                  ENV_FILE:
                          from_secret: "env_file"
                  USER:
                          from_secret: "ftp_user"
                  PASSWORD:
                          from_secret: "ftp_password"
                  SERVER:
                          from_secret: "ftp_server"
          when:
                  branch:
                          - "master"

image_pull_secrets:
        - "dockerconfigjson"
...
