---
image: "lehmannka/wetterobservatoriumweb:testing"

before_script:
        - "composer install"

static-analysis:
        script:
                - >-
                        /usr/bin/env php -dmemory_limit=-1 vendor/bin/phpstan
                        --level=max analyze config.php public/ src/ tests/

style-check:
        script:
                - >-
                        /usr/bin/env php vendor/bin/phpcs
                        --standard=PSR12 config.php public/api.php src/ tests/

unit_tests:
        script:
                - "/usr/bin/env php vendor/bin/phpunit tests/"
...
