# Simple docker-compose stack for the development of the application

---
version: "3.9"

services:
        node:
                build:
                        args:
                                NODE_VERSION: "20"
                        context: "."
                        target: "wo_node"
                command:
                        - "yarn"
                        - "run"
                        - "webpack"
                        - "--mode=development"
                        - "--watch"
                user: "node"
                volumes:
                        - ".:/application"
                working_dir: "/application"
        php:
                build:
                        args:
                                PHP_VERSION: "8.2"
                        context: "."
                        target: "wo_php"
                working_dir: "/application"
                volumes:
                        - ".:/application"
        web-apache:
                depends_on:
                        - "php"
                image: "httpd:alpine"
                ports:
                        - "8081:80"
                volumes:
                        - ".:/application:ro"
                        - "./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"
        web-nginx:
                depends_on:
                        - "php"
                image: "nginx:alpine"
                ports:
                        - "8080:80"
                volumes:
                        - ".:/application:ro"
                        - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
...
