# Simple docker-compose stack for the development of the application

---
version: "3.9"

services:
        php:
                build:
                        args:
                                PHP_VERSION: "8"
                        context: "."
                        target: "wo_php"
                depends_on:
                        - "db"
                volumes:
                        - ".:/application"
        web:
                depends_on:
                        - "php"
                image: "nginx:latest"
                ports:
                        - "8080:80"
                volumes:
                        - ".:/application"
                        - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
...
