---
name: "PHPStan static analysis"
author: "Karsten Lehmann <mail@kalehmann.de>"
description: "Static analysis of PHP code with PHPStan"
inputs:
        path:
                description: "The directories or files containing the code"
                required: true
runs:
        using: "docker"
        image: "../../../Dockerfile"
        entrypoint: "/bin/sh"
        args:
                - "-c"
                - >-
                        php -dmemory_limit=-1 vendor/bin/phpstan --level=max
                        analyze ${{ inputs.path }}
...
