parameters:

services:
        _defaults:
                autowire: true
                autoconfigure: true

        KaLehmann\WetterObservatoriumWeb\:
                resource: '../src/'
                exclude:
                        - '../src/DependencyInjection/'
                        - '../src/Entity/'
                        - '../src/Kernel.php'
                        - '../src/Tests/'

        KaLehmann\WetterObservatoriumWeb\Controller\:
                resource: '../src/Controller/'
                tags: ['controller.service_arguments']
