---
on: ["push"]

jobs:
        unit-tests:
                runs-on: "ubuntu-latest"
                name: "PHPUnit tests"
                steps:
                        - uses: "actions/checkout@v2"
                        - name: "PHPUnit tests"
                          id: "phpunit-tests"
                          uses: "./.github/actions/phpunit-tests"
...
